// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmpSyrQcuZvYPybMpEuD8zP38hV4Yc2bk',
    appId: '1:418775870803:web:e1eff68dcd3424ccaec5a6',
    messagingSenderId: '418775870803',
    projectId: 'libnotif-b6091',
    authDomain: 'libnotif-b6091.firebaseapp.com',
    databaseURL: 'https://libnotif-b6091-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'libnotif-b6091.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPL9FoMBuuCBaO_0Uc22J2nfN7aEU7h60',
    appId: '1:418775870803:android:e09b63e48fcf0d51aec5a6',
    messagingSenderId: '418775870803',
    projectId: 'libnotif-b6091',
    databaseURL: 'https://libnotif-b6091-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'libnotif-b6091.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDuRVYm4ZF9VS3cIapT6PhrFM5n6yZwZk',
    appId: '1:418775870803:ios:8df7e21d42de42a9aec5a6',
    messagingSenderId: '418775870803',
    projectId: 'libnotif-b6091',
    databaseURL: 'https://libnotif-b6091-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'libnotif-b6091.appspot.com',
    iosBundleId: 'com.example.libnotif',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDuRVYm4ZF9VS3cIapT6PhrFM5n6yZwZk',
    appId: '1:418775870803:ios:8df7e21d42de42a9aec5a6',
    messagingSenderId: '418775870803',
    projectId: 'libnotif-b6091',
    databaseURL: 'https://libnotif-b6091-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'libnotif-b6091.appspot.com',
    iosBundleId: 'com.example.libnotif',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmpSyrQcuZvYPybMpEuD8zP38hV4Yc2bk',
    appId: '1:418775870803:web:f66a078e0c12106baec5a6',
    messagingSenderId: '418775870803',
    projectId: 'libnotif-b6091',
    authDomain: 'libnotif-b6091.firebaseapp.com',
    databaseURL: 'https://libnotif-b6091-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'libnotif-b6091.appspot.com',
  );
}
